import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    const [transactionList, setTransactionList] = useState([]);
    const [address, setAddress] = useState('');

    const handleFormSubmit = async (event) => {
        event?.preventDefault();
        const response = await fetch(`/api/transaction-list/?address=${address}`, {
            headers: {
                'Content-Type': 'application/json',
            },
        });
        const responseData = await response.json();
        console.log(responseData);
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className={styles.main}>
                <h1>Transaction List</h1>
                <form onSubmit={handleFormSubmit}>
                    <label htmlFor='address'>Transaction address</label>
                    <input
                        type='text'
                        name='address'
                        value={address}
                        onChange={(event) => setAddress(event.target.value)}
                    />
                    <button type='submit'>Search</button>
                </form>
            </main>
        </>
    );
}
